### ISSUE TITLE
A bit faster would be nice.

### ISSUE THREAD

**Issue by rdebath** [mortim01/brainfuck#1]
![kaoulad-bf](https://user-images.githubusercontent.com/5853223/104245225-ccd1f100-545b-11eb-847d-ebc21012e490.gif)

This gif created with https://github.com/lecram/congif

**Comment by kaoulad** [comment]
Firstly, thanks for reporting the program slowness @rdebath.

This program has currently two optimizations, a light and a major optimization. The light optimization is in the output. I replaced the ``print`` used for ``.`` instruction to ``sys.stdout``. The major optimization is based on [Run-length encoding](https://en.wikipedia.org/wiki/Run-length_encoding), I grouped the consecutive and similar instructions, to create a compression without loss data and it's a huge gain time.

Old program (brainfuck.bf):
![Screenshot-2021-01-16-22-38-00.png](https://i.postimg.cc/fTfX61hM/Screenshot-2021-01-16-22-38-00.png)

New program (brainfuck.bf):
[![Screenshot-2021-01-16-22-55-06.png](https://i.postimg.cc/j2rw14gW/Screenshot-2021-01-16-22-55-06.png)](https://postimg.cc/gXN2X8Pd)

**Comment by rdebath** [comment]
Yes, RLE is a good one. Usually the next is `[-]` but you've already found that, what you haven't spotted yet is the `[>]` sequence. The mandelbrot program has a lot of those; with nine `>` or `<` codes (ie `[>>>>>>>>>]`).

The other two `[.]` and `[,]` are obviously useless, but noticing that you nearly always get a movement followed by a ADD or a LOOP can eliminate half of the instruction "decodes" you have to run. 

After that it gets more complicated.

**Comment by mortim01** [comment]
Thanks for reply, I'm going to look this.

**Comment by mortim01** [comment]
> 
> 
> Yes, RLE is a good one. Usually the next is `[-]` but you've already found that, what you haven't spotted yet is the `[>]` sequence. The mandelbrot program has a lot of those; with nine `>` or `<` codes (ie `[>>>>>>>>>]`).
> 
> The other two `[.]` and `[,]` are obviously useless, but noticing that you nearly always get a movement followed by a ADD or a LOOP can eliminate half of the instruction "decodes" you have to run.
> 
> After that it gets more complicated.

I commited and implemented the optimization of [>] and [<] sequence, I also implemented the [->>>+<<<] sequence and I grouped all move instructions (move right and move left) so  '>' it's an instruction like that (Move(1) and '<' it's an instruction like that (Move(-1)). ;)
